name: Build and Test

on:
  push:
    branches: [ "github-action" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish application
      run: dotnet publish --no-restore --configuration Release -o publish
    - name: Debug working directory
      run: pwd && ls -la
    - name: List contents of the publish directory
      run: ls -R ./publish || echo "Publish directory is empty"



  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy build artifacts to Raspberry Pi via ssh password
        uses: appleboy/scp-action@v0.1.7

        with:
          host: ${{ secrets.VISION_PI_HOST }}
          username: ${{ secrets.VISION_PI_USER }}
          key: ${{ secrets.VISION_PI_KEY }}
          source: /home/runner/work/local-deployment/local-deployment/publish
          target: ./srv
          debug: true



